### PR TITLE
update to sequelize v4

### PR DESCRIPTION
**Pull request by dan-nyanko**
- check instanceof on the prototype see
https://github.com/sequelize/sequelize/pull/5877
- update dependencies

### CODE REVIEW

**Comment by leodutra** [comment]
+1 for this pull.

**Comment by leodutra** [comment]
Created package sequelize-to-joi temporarily. @dan-nyanko

**Comment by andrewburgess** [comment]
Thanks for the PR, sorry I missed it until now. Going to bump version to v2 and publish it up

**Comment by leodutra** [comment]
Oh, thank you sir.

**Comment by leodutra** [comment]
Sequelize is now 4.8. I don't know if there's any relevant change, but as I cannot check right now, I'm pointing out.

**Comment by andrewburgess** [comment]
I think it should be alright. Nothing stood out in their changelog, but feel free to add an issue if any problems crop up

**Pull request merged**
