### PR TITLE
Add UUID and ARRAY types

### PR DESCRIPTION
**Pull request by Danlock**

### CODE REVIEW

**Comment by andrewburgess** [comment]
Thanks for this @Danlock!

**Comment by andrewburgess** [comment]
Released in [v1.0.1](https://github.com/RevoltTV/sequelize-to-joi/commit/340d101d5db95f68a20a3eef4224c2f6319cfebf)

**Comment by Danlock** [comment]
why not put this on npm?

**Comment by andrewburgess** [comment]
Whoops, sorry about that. It was private, opened it up (https://www.npmjs.com/package/@revolttv/sequelize-to-joi)

**Pull request merged**
